name: Build Library

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup build environment (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libomp-dev

    - name: Setup build environment (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install make
        choco install mingw

    - name: Find libgomp-1.dll (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $mingwPath = (Get-Command g++).Path.Replace('\bin\g++.exe', '')
        cp "$mingwPath\bin\libgomp-1.dll" .

    - name: Build library
      run: |
        cd cpp
        make

    - name: Archive library
      uses: actions/upload-artifact@v2
      with:
        name: mesh_render-library-${{ matrix.os }}
        path: |
          cpp/mesh_render.dll
          cpp/mesh_render.so
          cpp/*.o
          mesh_augmentator.py
          libgomp-1.dll
        if-no-files-found: ignore